version: '3.8'

services:
    server:
        build: .
        volumes: 
            - .:/app
        ports:
            - 8080:8080
        command: go run main.go
        healthcheck:
            test: curl -f http://localhost:8080/healthcheck || exit 1
            interval: 5s
            retries: 10
            timeout: 5s
    server_watcher:
        image: alpine
        depends_on:
            server:
                condition: service_healthy
        command: echo "SERVER LAUNCHED!"
